apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: ticketing-app-343318
  artifacts:
    - image: us.gcr.io/ticketing-app-343318/ticketing-auth
      context: ticketing-auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .